name: "CI"

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-12, macos-latest ]
        node-version: [ 16.17.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js ${{ matrix.node-version }} version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependency
        run: |
          yarn install
          yarn web install
          yarn server install

      - name: Build
        run: |
          CI=false yarn web build
          yarn server build
      - uses: mshick/add-pr-comment@v1
        if: ${{ failure() }}
        with:
          message: |
            ❌ Build failed.
            - OS: ${{ matrix.os }}
            - node.js: v${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true

      - uses: mshick/add-pr-comment@v1
        if: ${{ success() }}
        with:
          message: |
            ✨ Passed all.
            - OS: ${{ matrix.os }}
            - node.js: v${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true